### ISSUE TITLE
Failed to open file ... in text mode / in binary mode.

### ISSUE THREAD

**Issue by Gabriel-Lv258** [yuzhangbit/apollo_standalone#19]
@yuzhangbit @ytiang @zwkcoding 
Could you please kindly help to check the issue and share some comments ? When I going to execute ./open_space_palnner_demo, i meet the issue as shown below. 

WARNING: Logging before InitGoogleLogging() is written to STDERR
E1123 19:06:25.216426 28011 file.cc:73] [] Failed to open file /apollo/modules/planning/testdata/conf/open_space_standard_parking_lot.pb.txt in text mode.
E1123 19:06:25.216621 28011 file.cc:99] [] Failed to open file /apollo/modules/planning/testdata/conf/open_space_standard_parking_lot.pb.txt in binary mode.
E1123 19:06:25.216683 28011 file.cc:73] [] Failed to open file /apollo/modules/common/data/vehicle_param.pb.txt in text mode.
E1123 19:06:25.216729 28011 file.cc:99] [] Failed to open file /apollo/modules/common/data/vehicle_param.pb.txt in binary mode.
F1123 19:06:25.216755 28011 vehicle_config_helper.cc:37] Check failed: cyber::common::GetProtoFromFile(config_file, &params) Unable to parse vehicle config file /apollo/modules/common/data/vehicle_param.pb.txt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by 125663** [comment]
Hi, have you solved this problem ？i meet the problem too

**Comment by Gabriel-Lv258** [comment]
> Hi, have you solved this problem ？i meet the problem too

Yeah, this is not the code issue, it's caused by the directory path after you compiled the code.

**Comment by ZhouZijie77** [comment]
Hi, could you please tell me how you solved the problem? I meet the same problem, should I change some path?

**Comment by ZhouZijie-BIT** [comment]
problem solved

**Comment by ZhouZijie77** [comment]
> Hi, could you please tell me how you solved the problem? I meet the same problem, should I change some path?

Problem solved
